// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.1
// source: nationality/nationality.proto

package nationality

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	NationalityService_CreateNationalFood_FullMethodName       = "/nationality.NationalityService/CreateNationalFood"
	NationalityService_UpdateNationalFoods_FullMethodName      = "/nationality.NationalityService/UpdateNationalFoods"
	NationalityService_GetNationalFoodByID_FullMethodName      = "/nationality.NationalityService/GetNationalFoodByID"
	NationalityService_ListNationalFood_FullMethodName         = "/nationality.NationalityService/ListNationalFood"
	NationalityService_DeleteNationalFood_FullMethodName       = "/nationality.NationalityService/DeleteNationalFood"
	NationalityService_AddNationalFoodImage_FullMethodName     = "/nationality.NationalityService/AddNationalFoodImage"
	NationalityService_RemoveNationalFoodImage_FullMethodName  = "/nationality.NationalityService/RemoveNationalFoodImage"
	NationalityService_GetNationalFoodByCountry_FullMethodName = "/nationality.NationalityService/GetNationalFoodByCountry"
	NationalityService_SearchNationalFood_FullMethodName       = "/nationality.NationalityService/SearchNationalFood"
	NationalityService_GetRatingNationalFood_FullMethodName    = "/nationality.NationalityService/GetRatingNationalFood"
	NationalityService_AddHistorical_FullMethodName            = "/nationality.NationalityService/AddHistorical"
	NationalityService_UpdateHistoricals_FullMethodName        = "/nationality.NationalityService/UpdateHistoricals"
	NationalityService_GetHistoricalByID_FullMethodName        = "/nationality.NationalityService/GetHistoricalByID"
	NationalityService_ListHistorical_FullMethodName           = "/nationality.NationalityService/ListHistorical"
	NationalityService_DeleteHistorical_FullMethodName         = "/nationality.NationalityService/DeleteHistorical"
	NationalityService_SearchHistorical_FullMethodName         = "/nationality.NationalityService/SearchHistorical"
	NationalityService_GetHistoricalByCountry_FullMethodName   = "/nationality.NationalityService/GetHistoricalByCountry"
	NationalityService_AddHistoricalImage_FullMethodName       = "/nationality.NationalityService/AddHistoricalImage"
	NationalityService_RemoveHistoricalImage_FullMethodName    = "/nationality.NationalityService/RemoveHistoricalImage"
	NationalityService_CreateAttraction_FullMethodName         = "/nationality.NationalityService/CreateAttraction"
	NationalityService_UpdateAttractions_FullMethodName        = "/nationality.NationalityService/UpdateAttractions"
	NationalityService_GetAttractionByID_FullMethodName        = "/nationality.NationalityService/GetAttractionByID"
	NationalityService_ListAttraction_FullMethodName           = "/nationality.NationalityService/ListAttraction"
	NationalityService_DeleteAttraction_FullMethodName         = "/nationality.NationalityService/DeleteAttraction"
	NationalityService_AddAttractionImage_FullMethodName       = "/nationality.NationalityService/AddAttractionImage"
	NationalityService_RemoveAttractionImage_FullMethodName    = "/nationality.NationalityService/RemoveAttractionImage"
	NationalityService_SearchAttraction_FullMethodName         = "/nationality.NationalityService/SearchAttraction"
)

// NationalityServiceClient is the client API for NationalityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NationalityServiceClient interface {
	// National Foods
	CreateNationalFood(ctx context.Context, in *NationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error)
	UpdateNationalFoods(ctx context.Context, in *UpdateNationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error)
	GetNationalFoodByID(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*NationalFoodResponse, error)
	ListNationalFood(ctx context.Context, in *NationalFoodList, opts ...grpc.CallOption) (*NationalFoodListResponse, error)
	DeleteNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*Message, error)
	AddNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error)
	RemoveNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error)
	GetNationalFoodByCountry(ctx context.Context, in *NationalFoodCountry, opts ...grpc.CallOption) (*NationalFoodListResponse, error)
	SearchNationalFood(ctx context.Context, in *NationalFoodSearch, opts ...grpc.CallOption) (*NationalFoodListResponse, error)
	GetRatingNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*RatingResponse, error)
	// Historical
	AddHistorical(ctx context.Context, in *Historical, opts ...grpc.CallOption) (*HistoricalResponse, error)
	UpdateHistoricals(ctx context.Context, in *UpdateHistorical, opts ...grpc.CallOption) (*HistoricalResponse, error)
	GetHistoricalByID(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*HistoricalResponse, error)
	ListHistorical(ctx context.Context, in *HistoricalList, opts ...grpc.CallOption) (*HistoricalListResponse, error)
	DeleteHistorical(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*Message, error)
	SearchHistorical(ctx context.Context, in *HistoricalSearch, opts ...grpc.CallOption) (*HistoricalListResponse, error)
	GetHistoricalByCountry(ctx context.Context, in *HistoricalCountry, opts ...grpc.CallOption) (*HistoricalListResponse, error)
	AddHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error)
	RemoveHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error)
	// Attractions
	CreateAttraction(ctx context.Context, in *Attraction, opts ...grpc.CallOption) (*AttractionResponse, error)
	UpdateAttractions(ctx context.Context, in *UpdateAttraction, opts ...grpc.CallOption) (*AttractionResponse, error)
	GetAttractionByID(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*AttractionResponse, error)
	ListAttraction(ctx context.Context, in *AttractionList, opts ...grpc.CallOption) (*AttractionListResponse, error)
	DeleteAttraction(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*Message, error)
	AddAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error)
	RemoveAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error)
	SearchAttraction(ctx context.Context, in *AttractionSearch, opts ...grpc.CallOption) (*AttractionListResponse, error)
}

type nationalityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNationalityServiceClient(cc grpc.ClientConnInterface) NationalityServiceClient {
	return &nationalityServiceClient{cc}
}

func (c *nationalityServiceClient) CreateNationalFood(ctx context.Context, in *NationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NationalFoodResponse)
	err := c.cc.Invoke(ctx, NationalityService_CreateNationalFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) UpdateNationalFoods(ctx context.Context, in *UpdateNationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NationalFoodResponse)
	err := c.cc.Invoke(ctx, NationalityService_UpdateNationalFoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetNationalFoodByID(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*NationalFoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NationalFoodResponse)
	err := c.cc.Invoke(ctx, NationalityService_GetNationalFoodByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) ListNationalFood(ctx context.Context, in *NationalFoodList, opts ...grpc.CallOption) (*NationalFoodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NationalFoodListResponse)
	err := c.cc.Invoke(ctx, NationalityService_ListNationalFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) DeleteNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_DeleteNationalFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_AddNationalFoodImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) RemoveNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_RemoveNationalFoodImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetNationalFoodByCountry(ctx context.Context, in *NationalFoodCountry, opts ...grpc.CallOption) (*NationalFoodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NationalFoodListResponse)
	err := c.cc.Invoke(ctx, NationalityService_GetNationalFoodByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) SearchNationalFood(ctx context.Context, in *NationalFoodSearch, opts ...grpc.CallOption) (*NationalFoodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NationalFoodListResponse)
	err := c.cc.Invoke(ctx, NationalityService_SearchNationalFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetRatingNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*RatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, NationalityService_GetRatingNationalFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddHistorical(ctx context.Context, in *Historical, opts ...grpc.CallOption) (*HistoricalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalResponse)
	err := c.cc.Invoke(ctx, NationalityService_AddHistorical_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) UpdateHistoricals(ctx context.Context, in *UpdateHistorical, opts ...grpc.CallOption) (*HistoricalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalResponse)
	err := c.cc.Invoke(ctx, NationalityService_UpdateHistoricals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetHistoricalByID(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*HistoricalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalResponse)
	err := c.cc.Invoke(ctx, NationalityService_GetHistoricalByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) ListHistorical(ctx context.Context, in *HistoricalList, opts ...grpc.CallOption) (*HistoricalListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalListResponse)
	err := c.cc.Invoke(ctx, NationalityService_ListHistorical_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) DeleteHistorical(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_DeleteHistorical_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) SearchHistorical(ctx context.Context, in *HistoricalSearch, opts ...grpc.CallOption) (*HistoricalListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalListResponse)
	err := c.cc.Invoke(ctx, NationalityService_SearchHistorical_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetHistoricalByCountry(ctx context.Context, in *HistoricalCountry, opts ...grpc.CallOption) (*HistoricalListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalListResponse)
	err := c.cc.Invoke(ctx, NationalityService_GetHistoricalByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_AddHistoricalImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) RemoveHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_RemoveHistoricalImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) CreateAttraction(ctx context.Context, in *Attraction, opts ...grpc.CallOption) (*AttractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttractionResponse)
	err := c.cc.Invoke(ctx, NationalityService_CreateAttraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) UpdateAttractions(ctx context.Context, in *UpdateAttraction, opts ...grpc.CallOption) (*AttractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttractionResponse)
	err := c.cc.Invoke(ctx, NationalityService_UpdateAttractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetAttractionByID(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*AttractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttractionResponse)
	err := c.cc.Invoke(ctx, NationalityService_GetAttractionByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) ListAttraction(ctx context.Context, in *AttractionList, opts ...grpc.CallOption) (*AttractionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttractionListResponse)
	err := c.cc.Invoke(ctx, NationalityService_ListAttraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) DeleteAttraction(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_DeleteAttraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_AddAttractionImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) RemoveAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, NationalityService_RemoveAttractionImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) SearchAttraction(ctx context.Context, in *AttractionSearch, opts ...grpc.CallOption) (*AttractionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttractionListResponse)
	err := c.cc.Invoke(ctx, NationalityService_SearchAttraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NationalityServiceServer is the server API for NationalityService service.
// All implementations must embed UnimplementedNationalityServiceServer
// for forward compatibility
type NationalityServiceServer interface {
	// National Foods
	CreateNationalFood(context.Context, *NationalFood) (*NationalFoodResponse, error)
	UpdateNationalFoods(context.Context, *UpdateNationalFood) (*NationalFoodResponse, error)
	GetNationalFoodByID(context.Context, *NationalFoodId) (*NationalFoodResponse, error)
	ListNationalFood(context.Context, *NationalFoodList) (*NationalFoodListResponse, error)
	DeleteNationalFood(context.Context, *NationalFoodId) (*Message, error)
	AddNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error)
	RemoveNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error)
	GetNationalFoodByCountry(context.Context, *NationalFoodCountry) (*NationalFoodListResponse, error)
	SearchNationalFood(context.Context, *NationalFoodSearch) (*NationalFoodListResponse, error)
	GetRatingNationalFood(context.Context, *NationalFoodId) (*RatingResponse, error)
	// Historical
	AddHistorical(context.Context, *Historical) (*HistoricalResponse, error)
	UpdateHistoricals(context.Context, *UpdateHistorical) (*HistoricalResponse, error)
	GetHistoricalByID(context.Context, *HistoricalId) (*HistoricalResponse, error)
	ListHistorical(context.Context, *HistoricalList) (*HistoricalListResponse, error)
	DeleteHistorical(context.Context, *HistoricalId) (*Message, error)
	SearchHistorical(context.Context, *HistoricalSearch) (*HistoricalListResponse, error)
	GetHistoricalByCountry(context.Context, *HistoricalCountry) (*HistoricalListResponse, error)
	AddHistoricalImage(context.Context, *HistoricalImage) (*Message, error)
	RemoveHistoricalImage(context.Context, *HistoricalImage) (*Message, error)
	// Attractions
	CreateAttraction(context.Context, *Attraction) (*AttractionResponse, error)
	UpdateAttractions(context.Context, *UpdateAttraction) (*AttractionResponse, error)
	GetAttractionByID(context.Context, *AttractionId) (*AttractionResponse, error)
	ListAttraction(context.Context, *AttractionList) (*AttractionListResponse, error)
	DeleteAttraction(context.Context, *AttractionId) (*Message, error)
	AddAttractionImage(context.Context, *AttractionImage) (*Message, error)
	RemoveAttractionImage(context.Context, *AttractionImage) (*Message, error)
	SearchAttraction(context.Context, *AttractionSearch) (*AttractionListResponse, error)
	mustEmbedUnimplementedNationalityServiceServer()
}

// UnimplementedNationalityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNationalityServiceServer struct {
}

func (UnimplementedNationalityServiceServer) CreateNationalFood(context.Context, *NationalFood) (*NationalFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) UpdateNationalFoods(context.Context, *UpdateNationalFood) (*NationalFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNationalFoods not implemented")
}
func (UnimplementedNationalityServiceServer) GetNationalFoodByID(context.Context, *NationalFoodId) (*NationalFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNationalFoodByID not implemented")
}
func (UnimplementedNationalityServiceServer) ListNationalFood(context.Context, *NationalFoodList) (*NationalFoodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) DeleteNationalFood(context.Context, *NationalFoodId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) AddNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNationalFoodImage not implemented")
}
func (UnimplementedNationalityServiceServer) RemoveNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNationalFoodImage not implemented")
}
func (UnimplementedNationalityServiceServer) GetNationalFoodByCountry(context.Context, *NationalFoodCountry) (*NationalFoodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNationalFoodByCountry not implemented")
}
func (UnimplementedNationalityServiceServer) SearchNationalFood(context.Context, *NationalFoodSearch) (*NationalFoodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) GetRatingNationalFood(context.Context, *NationalFoodId) (*RatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) AddHistorical(context.Context, *Historical) (*HistoricalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) UpdateHistoricals(context.Context, *UpdateHistorical) (*HistoricalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHistoricals not implemented")
}
func (UnimplementedNationalityServiceServer) GetHistoricalByID(context.Context, *HistoricalId) (*HistoricalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoricalByID not implemented")
}
func (UnimplementedNationalityServiceServer) ListHistorical(context.Context, *HistoricalList) (*HistoricalListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) DeleteHistorical(context.Context, *HistoricalId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) SearchHistorical(context.Context, *HistoricalSearch) (*HistoricalListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) GetHistoricalByCountry(context.Context, *HistoricalCountry) (*HistoricalListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoricalByCountry not implemented")
}
func (UnimplementedNationalityServiceServer) AddHistoricalImage(context.Context, *HistoricalImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHistoricalImage not implemented")
}
func (UnimplementedNationalityServiceServer) RemoveHistoricalImage(context.Context, *HistoricalImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveHistoricalImage not implemented")
}
func (UnimplementedNationalityServiceServer) CreateAttraction(context.Context, *Attraction) (*AttractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) UpdateAttractions(context.Context, *UpdateAttraction) (*AttractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttractions not implemented")
}
func (UnimplementedNationalityServiceServer) GetAttractionByID(context.Context, *AttractionId) (*AttractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttractionByID not implemented")
}
func (UnimplementedNationalityServiceServer) ListAttraction(context.Context, *AttractionList) (*AttractionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) DeleteAttraction(context.Context, *AttractionId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) AddAttractionImage(context.Context, *AttractionImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAttractionImage not implemented")
}
func (UnimplementedNationalityServiceServer) RemoveAttractionImage(context.Context, *AttractionImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAttractionImage not implemented")
}
func (UnimplementedNationalityServiceServer) SearchAttraction(context.Context, *AttractionSearch) (*AttractionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) mustEmbedUnimplementedNationalityServiceServer() {}

// UnsafeNationalityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NationalityServiceServer will
// result in compilation errors.
type UnsafeNationalityServiceServer interface {
	mustEmbedUnimplementedNationalityServiceServer()
}

func RegisterNationalityServiceServer(s grpc.ServiceRegistrar, srv NationalityServiceServer) {
	s.RegisterService(&NationalityService_ServiceDesc, srv)
}

func _NationalityService_CreateNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFood)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).CreateNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_CreateNationalFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).CreateNationalFood(ctx, req.(*NationalFood))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_UpdateNationalFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNationalFood)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).UpdateNationalFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_UpdateNationalFoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).UpdateNationalFoods(ctx, req.(*UpdateNationalFood))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetNationalFoodByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetNationalFoodByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_GetNationalFoodByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetNationalFoodByID(ctx, req.(*NationalFoodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_ListNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).ListNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_ListNationalFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).ListNationalFood(ctx, req.(*NationalFoodList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_DeleteNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).DeleteNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_DeleteNationalFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).DeleteNationalFood(ctx, req.(*NationalFoodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddNationalFoodImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddNationalFoodImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_AddNationalFoodImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddNationalFoodImage(ctx, req.(*NationalFoodImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_RemoveNationalFoodImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).RemoveNationalFoodImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_RemoveNationalFoodImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).RemoveNationalFoodImage(ctx, req.(*NationalFoodImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetNationalFoodByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetNationalFoodByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_GetNationalFoodByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetNationalFoodByCountry(ctx, req.(*NationalFoodCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_SearchNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).SearchNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_SearchNationalFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).SearchNationalFood(ctx, req.(*NationalFoodSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetRatingNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetRatingNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_GetRatingNationalFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetRatingNationalFood(ctx, req.(*NationalFoodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Historical)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_AddHistorical_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddHistorical(ctx, req.(*Historical))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_UpdateHistoricals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHistorical)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).UpdateHistoricals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_UpdateHistoricals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).UpdateHistoricals(ctx, req.(*UpdateHistorical))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetHistoricalByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetHistoricalByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_GetHistoricalByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetHistoricalByID(ctx, req.(*HistoricalId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_ListHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).ListHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_ListHistorical_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).ListHistorical(ctx, req.(*HistoricalList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_DeleteHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).DeleteHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_DeleteHistorical_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).DeleteHistorical(ctx, req.(*HistoricalId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_SearchHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).SearchHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_SearchHistorical_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).SearchHistorical(ctx, req.(*HistoricalSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetHistoricalByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetHistoricalByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_GetHistoricalByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetHistoricalByCountry(ctx, req.(*HistoricalCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddHistoricalImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddHistoricalImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_AddHistoricalImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddHistoricalImage(ctx, req.(*HistoricalImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_RemoveHistoricalImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).RemoveHistoricalImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_RemoveHistoricalImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).RemoveHistoricalImage(ctx, req.(*HistoricalImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_CreateAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attraction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).CreateAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_CreateAttraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).CreateAttraction(ctx, req.(*Attraction))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_UpdateAttractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttraction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).UpdateAttractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_UpdateAttractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).UpdateAttractions(ctx, req.(*UpdateAttraction))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetAttractionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetAttractionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_GetAttractionByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetAttractionByID(ctx, req.(*AttractionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_ListAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).ListAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_ListAttraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).ListAttraction(ctx, req.(*AttractionList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_DeleteAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).DeleteAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_DeleteAttraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).DeleteAttraction(ctx, req.(*AttractionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddAttractionImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddAttractionImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_AddAttractionImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddAttractionImage(ctx, req.(*AttractionImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_RemoveAttractionImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).RemoveAttractionImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_RemoveAttractionImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).RemoveAttractionImage(ctx, req.(*AttractionImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_SearchAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).SearchAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NationalityService_SearchAttraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).SearchAttraction(ctx, req.(*AttractionSearch))
	}
	return interceptor(ctx, in, info, handler)
}

// NationalityService_ServiceDesc is the grpc.ServiceDesc for NationalityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NationalityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nationality.NationalityService",
	HandlerType: (*NationalityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNationalFood",
			Handler:    _NationalityService_CreateNationalFood_Handler,
		},
		{
			MethodName: "UpdateNationalFoods",
			Handler:    _NationalityService_UpdateNationalFoods_Handler,
		},
		{
			MethodName: "GetNationalFoodByID",
			Handler:    _NationalityService_GetNationalFoodByID_Handler,
		},
		{
			MethodName: "ListNationalFood",
			Handler:    _NationalityService_ListNationalFood_Handler,
		},
		{
			MethodName: "DeleteNationalFood",
			Handler:    _NationalityService_DeleteNationalFood_Handler,
		},
		{
			MethodName: "AddNationalFoodImage",
			Handler:    _NationalityService_AddNationalFoodImage_Handler,
		},
		{
			MethodName: "RemoveNationalFoodImage",
			Handler:    _NationalityService_RemoveNationalFoodImage_Handler,
		},
		{
			MethodName: "GetNationalFoodByCountry",
			Handler:    _NationalityService_GetNationalFoodByCountry_Handler,
		},
		{
			MethodName: "SearchNationalFood",
			Handler:    _NationalityService_SearchNationalFood_Handler,
		},
		{
			MethodName: "GetRatingNationalFood",
			Handler:    _NationalityService_GetRatingNationalFood_Handler,
		},
		{
			MethodName: "AddHistorical",
			Handler:    _NationalityService_AddHistorical_Handler,
		},
		{
			MethodName: "UpdateHistoricals",
			Handler:    _NationalityService_UpdateHistoricals_Handler,
		},
		{
			MethodName: "GetHistoricalByID",
			Handler:    _NationalityService_GetHistoricalByID_Handler,
		},
		{
			MethodName: "ListHistorical",
			Handler:    _NationalityService_ListHistorical_Handler,
		},
		{
			MethodName: "DeleteHistorical",
			Handler:    _NationalityService_DeleteHistorical_Handler,
		},
		{
			MethodName: "SearchHistorical",
			Handler:    _NationalityService_SearchHistorical_Handler,
		},
		{
			MethodName: "GetHistoricalByCountry",
			Handler:    _NationalityService_GetHistoricalByCountry_Handler,
		},
		{
			MethodName: "AddHistoricalImage",
			Handler:    _NationalityService_AddHistoricalImage_Handler,
		},
		{
			MethodName: "RemoveHistoricalImage",
			Handler:    _NationalityService_RemoveHistoricalImage_Handler,
		},
		{
			MethodName: "CreateAttraction",
			Handler:    _NationalityService_CreateAttraction_Handler,
		},
		{
			MethodName: "UpdateAttractions",
			Handler:    _NationalityService_UpdateAttractions_Handler,
		},
		{
			MethodName: "GetAttractionByID",
			Handler:    _NationalityService_GetAttractionByID_Handler,
		},
		{
			MethodName: "ListAttraction",
			Handler:    _NationalityService_ListAttraction_Handler,
		},
		{
			MethodName: "DeleteAttraction",
			Handler:    _NationalityService_DeleteAttraction_Handler,
		},
		{
			MethodName: "AddAttractionImage",
			Handler:    _NationalityService_AddAttractionImage_Handler,
		},
		{
			MethodName: "RemoveAttractionImage",
			Handler:    _NationalityService_RemoveAttractionImage_Handler,
		},
		{
			MethodName: "SearchAttraction",
			Handler:    _NationalityService_SearchAttraction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nationality/nationality.proto",
}
